#!/usr/bin/python3

import sys
import argparse
import os.path
from pwd import getpwnam
from lib import Settings, PACKAGE, PACKAGE_NAME, PACKAGE_VERSION, utils
from lib.logger import Logger, ConsoleLogger, ConfirmPromptBuilder
from lib.exceptions import ConfigurationError, ControlException
from lib.pid_file import PIDFile
from lib import utils
from lib.control import BaseControl
from lib.hwmon import HwmonProvider


class PermissionManager(BaseControl):
    def __init__(self, settings, logger, console):
        super().__init__(settings, logger, HwmonProvider, auto_load=True)
        self.console = console


    def load_dependencies(self):
        HwmonProvider.configure(self.settings, self.logger)
        if not HwmonProvider.load():
            raise ConfigurationError('HwmonProvider failed to complete loading')
        return super().load_dependencies()


    def check_pid(self, pid_file, zap_if_exists) -> bool:
        if os.path.isfile(pid_file):
            remove_pid = zap_if_exists
            if not remove_pid:
                self.logger.log('PID file \'{}\' already exists, should it be removed?'.format(pid_file), log_level=Logger.WARNING)
                input = self.console.prompt_choices(ConfirmPromptBuilder(self.console, include_cancel=False), prompt='Remove existing PID')
                if input == 'y':
                    remove_pid = True
            if remove_pid:
                os.remove(pid_file)
                self.logger.log('{} removed'.format(pid_file), log_level=Logger.WARNING)
                return True
            return False
        return True


    def check_user(self, new_user):
        try:
            return getpwnam(new_user)
        except KeyError:
            raise ControlException('No such user: {}'.format(new_user))


    def perform_chown(self, user):
        for output in self.outputs.values():
            for path in output.hwmon_object.get_permission_paths():
                self.__chown_file(user, path)


    def __chown_file(self, user_details, file):
        if os.path.isfile(file):
            file_stat = os.stat(file)
            uid = file_stat.st_uid
            gid = file_stat.st_gid
            if uid != user_details.pw_uid:
                os.chown(file, user_details.pw_uid, gid)
                self.logger.log('Changed owner for {} to {} (uid={})'.format(file, user_details.pw_name, user_details.pw_uid), log_level=Logger.WARNING)


def main():
    parser = argparse.ArgumentParser()
    parser.description = '''
    Python fancontrol, spinning fans in the 21st century. Specifically
    intended for importing configuration generated by original package.
    '''
    parser.add_argument('-c', '--config-path', type=utils.is_existing_config, default='fancontrol.ini', help='Specify configuration')
    parser.add_argument('--pid-file', type=utils.is_pid, default='fancontrol.pid', help='Specify pid path')
    parser.add_argument('-z', '--zap-pid', action='store_true', help='Remove pid if it exists')
    parser.add_argument('-u', '--user', help='Specify user that should own hwmon entries', required=True)
    utils.add_interactive_arguments(parser)
    args = parser.parse_args()

    logger = utils.get_interactive_logger(PACKAGE_NAME, args)
    try:
        logger = utils.get_logger(PACKAGE_NAME, args, ConsoleLogger)
        settings = Settings(args.config_path, logger, reconfigure_logger=False)
        console = utils.get_interactive_logger(PACKAGE_NAME, args, auto_flush=True)
        logger.log('{} checking permissions...'.format(PermissionManager.__name__))
        manager = PermissionManager(settings, logger, console)

        # Check PID
        if not manager.check_pid(args.pid_file, zap_if_exists=args.zap_pid):
            console.log_error('PID exists but not removed, exiting...')
            sys.exit(1)

        # Lookup user
        try:
            user_details = manager.check_user(args.user)
        except ControlException as e:
            console.log_error(str(e))
            sys.exit(1)

        # Change file permissions
        manager.perform_chown(user_details)

    except ConfigurationError as e:
        console.log_error('Problem in configuration:')
        console.log_direct('\t' + str(e))
        sys.exit(1)
    except ControlException as e:
        logger.log('Uncaught exception: ' + str(e), Logger.ERROR)
        sys.exit(1)

    
if __name__ == "__main__":
    main()
