#!/usr/bin/python3

import argparse
import os
from pathlib import Path
from lib import Logger, ConsoleLogger, Settings, PACKAGE_VERSION


def is_ini(config_path):
    '''
    Configuration might not exist yet, so we only test extension.
    '''
    if not config_path.lower().endswith('.ini'):
        raise argparse.ArgumentError("Unknown extension specified (" + config_path + ")")
    return config_path


def is_config(config_path):
    '''
    Check that the specified configuration file exists
    '''
    if not os.path.isfile(config_path):
        raise argparse.ArgumentError("No suitable file specified (" + config_path + ")")
    return config_path


def main():
    parser = argparse.ArgumentParser()
    parser.description = '''
    Python fancontrol, spinning fans in the 21st century. Specifically
    intended for importing configuration generated by original package.
    '''
    parser.add_argument('-c', '--config-path', type=is_ini, default='py_fancontrol.ini', help='Specify configuration')
    parser.add_argument('-i', '--input-path', type=is_config, default="/etc/fancontrol", help='Specify configuration')
    parser.add_argument('-v', '--version', action='version', version=PACKAGE_VERSION, help="Show version information")
    args = parser.parse_args()

    logger = ConsoleLogger()
    settings = Settings(args.config_path, logger)
    settings.import_configuration(args.input_path)
    
if __name__ == "__main__":
    main()
