#!/usr/bin/python3

import sys
import argparse
import os
from pathlib import Path
from lib import Logger, ConsoleLogger, Settings, PACKAGE_VERSION


def is_ini(config_path):
    '''
    Configuration might not exist yet, so we only test extension.
    '''
    if not config_path.lower().endswith('.ini'):
        raise argparse.ArgumentError("Unknown extension specified (" + config_path + ")")
    return config_path


def is_config(config_path):
    '''
    Check that the specified configuration file exists
    '''
    if not os.path.isfile(config_path):
        raise argparse.ArgumentError("No suitable file specified (" + config_path + ")")
    return config_path


def main():
    parser = argparse.ArgumentParser()
    parser.description = '''
    Python fancontrol, spinning fans in the 21st century. Specifically
    intended for importing configuration generated by original package.
    '''
    parser.add_argument('-c', '--config-path', type=is_ini, default='fancontrol.ini', help='Specify configuration')
    parser.add_argument('-i', '--import-path', type=is_config, default="/etc/fancontrol", help='Specify configuration')
    parser.add_argument('-v', '--version', action='version', version=PACKAGE_VERSION, help="Show version information")
    parser.add_argument('--replace', action='store_true', help="Replaces configuration")
    args = parser.parse_args()

    logger = ConsoleLogger()

    if os.path.isfile(args.config_path) and not args.replace:
        logger.log(Logger.to_key_value('Configuration path already exists', args.config_path), Logger.ERROR)
        sys.exit(1) 

    config_tmp = args.config_path + '.tmp'
    if (os.path.isfile(config_tmp)):
        logger.log(Logger.to_key_value('Removing temporary configuration', config_tmp), Logger.WARNING)
        os.remove(config_tmp)

    settings = Settings(config_tmp, logger)
    settings.import_configuration(args.import_path)

    os.rename(config_tmp, args.config_path)
    
if __name__ == "__main__":
    main()
